#!/usr/bin/bash

# Build & install project.
mkdir -p build
cd build
cmake ..
make
make install
cd ..

# Start linuxcnc environment.
cd ../../scripts/ && . ./rip-environment
cd ../bin

halcmd stop
halcmd loadrt threads name1=servo-thread fp1=0 period1=1000000

halcmd loadusr -W lcec_conf /home/user/linuxcnc_distro_files/linuxcnc/cmake/libcia402/ethercat-conf.xml
halcmd loadrt lcec
halcmd loadrt cia402 count=1

halcmd addf lcec.read-all servo-thread
halcmd addf cia402.read-all servo-thread

halcmd addf cia402.write-all servo-thread
halcmd addf lcec.write-all servo-thread

#halcmd setp cia402.0.csp-mode 1
halcmd setp cia402.0.pos-scale 100000
#halcmd setp lcec.0.0.max-torque 100  # Range:0-3500
#halcmd setp lcec.0.0.homing-method 35  # Range:0-35

#from servo(ethercat) to cia402
halcmd net x-statusword lcec.0.0.cia-statusword cia402.0.statusword
halcmd net x-opmode-display lcec.0.0.opmode-display cia402.0.opmode-display
halcmd net x-drv-act-pos lcec.0.0.actual-position cia402.0.drv-actual-position
halcmd net x-drv-act-velo lcec.0.0.actual-velocity cia402.0.drv-actual-velocity

#from cia402 to servo(ethercat) 
halcmd net x-controlword cia402.0.controlword lcec.0.0.cia-controlword
halcmd net x-modes-of-operation cia402.0.opmode lcec.0.0.opmode
halcmd net x-drv-target-pos cia402.0.drv-target-position lcec.0.0.target-position
halcmd net x-drv-target-velo cia402.0.drv-target-velocity lcec.0.0.target-velocity

#from motion to cia
#net x-enable    <= joint.0.amp-enable-out => cia402.0.enable
#net x-amp-fault => joint.0.amp-fault-in   <= cia402.0.drv-fault
#net x-pos-cmd   <= joint.0.motor-pos-cmd  => cia402.0.pos-cmd
#net x-pos-fb    => joint.0.motor-pos-fb   <= cia402.0.pos-fb

#homing
#net x-home-index <= joint.0.index-enable  => cia402.0.home

halcmd start

#halcmd show
halshow

halrun -U

# To clean the hal environment :
# ~/linuxcnc/scripts/halrun -U
