#!/usr/bin/bash

# Build & install project.
mkdir -p build
cd build
cmake ..
make
make install
cd ..

# Start linuxcnc environment.
cd ../../scripts/ && . ./rip-environment
cd ../bin

halcmd stop
halcmd loadrt threads name1=base-thread fp1=0 period1=25000 name2=servo-thread period2=1000000
halcmd loadrt template
halcmd addf template_update servo-thread
halcmd start

halcmd show

# To clean the hal environment :
# ~/linuxcnc/scripts/halrun -U
