#!/bin/bash

# Get current directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Path to config file relative to script location
CONFIG="${SCRIPT_DIR}/axis_9_3_spindles/axis_9_3_spindles.ini"
cd ../../..
cd scripts
. ./rip-environment
linuxcnc $CONFIG





