#!/bin/bash

# New things.
sudo apt-get -y install libgl1-mesa-dev
sudo apt-get -y install python3-gi-cairo
sudo apt-get -y install python3-opengl

# Debian 13
sudo apt-get -y install gpiod-dev gpiod

# Eigen math library.
sudo apt-get -y install libeigen3-dev

# Ceres non linear solver.
sudo apt-get -y install libceres-dev

# Linuxcnc gscreen
sudo apt-get -y install libgtksourceview-4-dev gir1.2-gtksource-4

# https://www.linuxcnc.org/docs/devel/html/code/building-linuxcnc.html
cd .. # Up to source dir.
sudo apt-get update
sudo apt-get -y install build-essential git cmake
sudo apt-get -y install dpkg-dev

./debian/configure
sudo apt-get build-dep . -y

cd cmake # Back to cmake dir.





